version: 2.1

orbs:
   gem-tool: appfolio/gem-tool@volatile

workflows:
  rc:
    jobs:
      - gem-tool/checkout_bundle_install_appraisal_rspec:
          name: test-ruby-271
          context: appfolio_test_context
          executor_tag: gem-tool/ruby_base_271
          gem_name: 'swagger/blocks'
      - gem-tool/checkout_bundle_install_appraisal_rspec:
          name: test-ruby-263
          context: appfolio_test_context
          executor_tag: gem-tool/ruby_base_263
          gem_name: 'swagger/blocks'
