version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
        auth:
          username: "$DOCKERHUB_USER"
          password: "$DOCKERHUB_PASSWORD"
      - image: circleci/mysql:5.6
        auth:
          username: "$DOCKERHUB_USER"
          password: "$DOCKERHUB_PASSWORD"
    executor: ruby/default
    steps:
      - checkout
      - run: sudo gem update --system
      - run: bundle install
      - run: bundle exec rspec

workflows:
  rc:
    jobs:
      - build:
          context: appfolio_test_context
